format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

add_newline = false

[username]
style_root = 'red'
style_user = 'orange'
format = '[$user]($style)'

[hostname]
style = 'orange'
format = '[@$hostname]($style) '

[directory]
style = 'green'

[git_branch]
style = "orange"
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[<](bold green)'

